[package]
name = "arty_exx"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]

[dependencies]
sifive = { path = "../sifive" }
riscv32i = { path = "../../arch/riscv32i" }
kernel = { path = "../../kernel" }

